// cryptomus
package cryptomus

const (
	urlEndpoint                       = "https://api.cryptomus.com/"
	urlCreateInvoice                  = "https://api.cryptomus.com/v1/payment"
	urlCreateStaticWallet             = "https://api.cryptomus.com/v1/wallet"
	urlGenerateQRCodeForStaticWallet  = "https://api.cryptomus.com/v1/wallet/qr"
	urlGenerateQRCodeForInvoice       = "https://api.cryptomus.com/v1/payment/qr"
	urlBlockStaticWallet              = "https://api.cryptomus.com/v1/wallet/block-address"
	urlRefundBlockedAddress           = "https://api.cryptomus.com/v1/wallet/blocked-address-refund"
	urlGetPaymentInformation          = "https://api.cryptomus.com/v1/payment/info"
	urlRefund                         = "https://api.cryptomus.com/v1/payment/refund"
	urlResendWebhook                  = "https://api.cryptomus.com/v1/payment/resend"
	urlTestWebhookPayment             = "https://api.cryptomus.com/v1/test-webhook/payment"
	urlTestWebhookPayout              = "https://api.cryptomus.com/v1/test-webhook/payout"
	urlTestWebhookWallet              = "https://api.cryptomus.com/v1/test-webhook/wallet"
	urlListPaymentServices            = "https://api.cryptomus.com/v1/payment/services"
	urlListPaymentHistory             = "https://api.cryptomus.com/v1/payment/list"
	urlCreatePayout                   = "https://api.cryptomus.com/v1/payout"
	urlGetPayoutInformation           = "https://api.cryptomus.com/v1/payout/info"
	urlListPayoutHistory              = "https://api.cryptomus.com/v1/payout/list"
	urlListPayoutServices             = "https://api.cryptomus.com/v1/payout/services"
	urlTransferToPersonalWallet       = "https://api.cryptomus.com/v1/transfer/to-personal"
	urlTransferToBusinessWallet       = "https://api.cryptomus.com/v1/transfer/to-business"
	urlCreateRecurringPayment         = "https://api.cryptomus.com/v1/recurrence/create"
	urlGetRecurringPaymentInformation = "https://api.cryptomus.com/v1/recurrence/info"
	urlListRecurringPayments          = "https://api.cryptomus.com/v1/recurrence/list"
	urlCancelRecurringPayment         = "https://api.cryptomus.com/v1/recurrence/cancel"
	urlGetExchangeRate                = "https://api.cryptomus.com/v1/exchange-rate/%s/list"
	urlListDiscounts                  = "https://api.cryptomus.com/v1/payment/discount/list"
	urlSetDiscount                    = "https://api.cryptomus.com/v1/payment/discount/set"
	urlGetBalanceForMerchant          = "https://api.cryptomus.com/v1/balance"
	urlGetAssets                      = "https://api.cryptomus.com/v1/exchange/market/assets"
	urlGetOrderBook                   = "https://api.cryptomus.com/v1/exchange/market/order-book/%s"
	urlGetTrades                      = "https://api.cryptomus.com/v1/exchange/market/trades/%s"
	urlGetBalanceForUser              = "https://api.cryptomus.com/v2/user-api/balance"
	urlCalculateConvert               = "https://api.cryptomus.com/v2/user-api/convert/calculate"
	urlCreateMarketOrder              = "https://api.cryptomus.com/v2/user-api/convert/"
	urlCreateLimitOrder               = "https://api.cryptomus.com/v2/user-api/convert/limit"
	urlCancelLimitOrder               = "https://api.cryptomus.com/v2/user-api/convert/%s"
	urlListDirections                 = "https://api.cryptomus.com/v2/user-api/convert/direction-list"
	urlListOrderHistory               = "https://api.cryptomus.com/v2/user-api/convert/order-list/"
)
